modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="factorycore"
version="${version}"
displayName="Factory Core"
description='''Shared storage and automation. Development bootstrap; gameplay is not implemented.'''

[[dependencies.factorycore]]
modId="neoforge"
type="required"
versionRange="[21.1.252]"
ordering="NONE"
side="BOTH"

[[dependencies.factorycore]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
